version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-nginx
    ports:
      - "8080:80"
  dynamicServer:
    build:
      context: dynamicServer/
      dockerfile: Dockerfile
    image: http-api
    ports:
      - "7001:7001"
