version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: static_server
    expose:
      - "1080"
    labels:
    # Link to access the page: localhost
      - "traefik.http.routers.web.rule=Host(`localhost`)"
      - "traefik.http.services.web.loadbalancer.server.port=1080"
      - "traefik.http.routers.web.entrypoints=http,https"
      - "traefik.http.routers.web.tls=true"
    deploy:
      replicas: 2
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:latest
    # Enables the web UI and tells Traefik to listen to docker
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/certificates:/etc/traefik/certificates
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml
  dynamicServer:
    build:
      context: dynamicServer/
      dockerfile: Dockerfile
    image: http-api
    expose:
      - "7001"
    labels:
      # Redirects all packets going to the "/api" entrypoint to port 7001.
      # The API is therefore available at localhost/api, so it is possible to access localhost/api/animals.
      - "traefik.http.routers.dynamicServer.rule=PathPrefix(`/api`)"
      - "traefik.http.services.dynamicServer.loadbalancer.server.port=7001"
      - "traefik.http.services.dynamicServer.loadbalancer.sticky.cookie=true"
      - "traefik.http.services.dynamicServer.loadbalancer.sticky.cookie.name=dynamicServerCookie"
      - "traefik.http.routers.dynamicServer.entrypoints=http,https"
      - "traefik.http.routers.dynamicServer.tls=true"
    deploy:
      replicas: 2
  portainer:
    image: portainer/portainer-ce
    expose:
      - "9000"  # Port pour accéder à l'interface utilisateur de Portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
    # To connect to portainer: enter portainer.localhost
    - "traefik.http.routers.portainer.rule=Host(`portainer.localhost`)"
    - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    - "traefik.http.routers.portainer.entrypoints=http,https"
    - "traefik.http.routers.portainer.tls=true"
volumes:
  portainer_data:
  certificates:
  traefik: