providers:
  docker: {}

entrypoints:
  http: 
    address: ":80"
  https:
    address: ":443"

tls:
  certificates:
    - certFile: /certificates/cert.pem
      keyFile: /certificates/key.pem
api:
  dashboard: true
  insecure: true